# Generated by Django 5.2.3 on 2025-07-27 16:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0002_carteira_vendaficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sange')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Sange',
                'verbose_name_plural': 'Sanges',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CaixaSange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('fichas_iniciais', models.JSONField(default=dict, verbose_name='Fichas Iniciais')),
                ('valor_total_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total Inicial')),
                ('fichas_atuais', models.JSONField(default=dict, verbose_name='Fichas Atuais')),
                ('valor_total_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total Atual')),
                ('sange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sange.sange', verbose_name='Sange')),
            ],
            options={
                'verbose_name': 'Caixa de Sange',
                'verbose_name_plural': 'Caixas de Sange',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='TrocaFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor Original')),
                ('valor_ficha_troca', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor da Ficha de Troca')),
                ('quantidade_gerada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade Gerada')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Troca')),
                ('caixa_sange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sange.caixasange', verbose_name='Caixa da Sange')),
            ],
            options={
                'verbose_name': 'Troca de Ficha',
                'verbose_name_plural': 'Trocas de Fichas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='VendaFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor Unitário da Ficha')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('caixa_sange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sange.caixasange', verbose_name='Caixa da Sange')),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.cliente', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Venda de Ficha',
                'verbose_name_plural': 'Vendas de Fichas',
                'ordering': ['-data'],
            },
        ),
    ]
