# Generated by Django 5.2.3 on 2025-09-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trocaficha',
            name='detalhes',
            field=models.JSONField(default=dict, verbose_name='Detalhes da Troca (origem)'),
        ),
    ]
