# Generated by Django 5.2.3 on 2025-07-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jogo', models.CharField(choices=[('poker', 'Poker'), ('caribenho', 'Poker Caribenho'), ('ultimate', 'Poker Ultimate'), ('baccarat', 'Baccarat'), ('roleta', 'Roleta')], max_length=20, verbose_name='Tipo de Jogo')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('encerrada', 'Encerrada')], default='aberta', max_length=20, verbose_name='Status')),
                ('numero_mesa', models.IntegerField(verbose_name='Número da Mesa')),
                ('fichas_5', models.IntegerField(default=0, verbose_name='Fichas de R$ 5')),
                ('fichas_25', models.IntegerField(default=0, verbose_name='Fichas de R$ 25')),
                ('fichas_100', models.IntegerField(default=0, verbose_name='Fichas de R$ 100')),
                ('fichas_500', models.IntegerField(default=0, verbose_name='Fichas de R$ 500')),
                ('fichas_1000', models.IntegerField(default=0, verbose_name='Fichas de R$ 1.000')),
                ('fichas_5000', models.IntegerField(default=0, verbose_name='Fichas de R$ 5.000')),
                ('fichas_10000', models.IntegerField(default=0, verbose_name='Fichas de R$ 10.000')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total da Mesa')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Inicial da Mesa')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo da Mesa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero_mesa'],
            },
        ),
    ]
