# Generated by Django 5.2.3 on 2025-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='croupier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Croupier'),
        ),
    ]
