# Generated by Django 5.2.3 on 2025-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('encerrada', 'Encerrada')], default='aberta', max_length=20, verbose_name='Status'),
        ),
    ]
