# Generated by Django 5.2.3 on 2025-08-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croupiers', '0001_initial'),
        ('mesas', '0002_mesa_croupier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='croupier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='croupiers.croupier', verbose_name='Croupier'),
        ),
    ]
