# Generated by Django 5.2.3 on 2025-07-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_alter_mesa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo da Mesa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Inicial da Mesa'),
        ),
    ]
