# Generated by Django 5.2.3 on 2025-08-30 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croupiers', '0001_initial'),
        ('mesas', '0003_alter_mesa_croupier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSaldoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Inicial no Momento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total no Momento')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo no Momento')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('croupier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='croupiers.croupier', verbose_name='Croupier')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saldo', to='mesas.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Registro de Saldo da Mesa',
                'verbose_name_plural': 'Registros de Saldo das Mesas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
