# Generated by Django 5.2.3 on 2025-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0004_mesa_saldo_mesa_valor_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero_mesa',
            field=models.IntegerField(verbose_name='Número da Mesa'),
        ),
    ]
